### ISSUE TITLE
Please add options to download python or jupyter notebook files for examples under Embedding section

### ISSUE THREAD

**Issue by RGPATCHI** [ansys/pymechanical-embedding-examples#63]
### Description of the modifications

For the example under Embedding (link below) these download options are missing at the bottom of the webpage. Its available for examples under Remote. 

https://embedding.examples.mechanical.docs.pyansys.com/basic_examples/basic/ex_01-valve.html#sphx-glr-ex-01-valve-py

**Comment by RobPasMue** [comment]
Please work on this @dipinknair - we should enable those download buttons. Refer to the PyMechanical implementation - they have it implemented


For example: 
https://mechanical.docs.pyansys.com/version/stable/examples/gallery_examples/00_basic/example_01_simple_structural_solve.html#sphx-glr-examples-gallery-examples-00-basic-example-01-simple-structural-solve-py
